//! Low-level ScriptingBridge glue.
//!
//! All items here are `pub(super)` — they are internal to the `notes` module.

#![allow(non_snake_case)]

use objc2::rc::Retained;
use objc2::runtime::AnyObject;
use objc2::{extern_class, msg_send};
use objc2_foundation::{NSObject, NSString};

use super::types::{AccountInfo, AttachmentInfo, FolderInfo, NoteInfo};

// ─── Link ScriptingBridge framework ──────────────────────────────────────────

#[link(name = "ScriptingBridge", kind = "framework")]
unsafe extern "C" {}

// ─── Minimal ScriptingBridge class declarations ───────────────────────────────
//
// objc2 has no pre-generated crate for ScriptingBridge, so we declare the two
// root classes manually.  Notes-specific proxy types are generated by the runtime
// and accessed as AnyObject.

extern_class!(
    #[unsafe(super(NSObject))]
    pub struct SBObject;
);

extern_class!(
    #[unsafe(super(SBObject, NSObject))]
    pub struct SBApplication;
);

// ─── Low-level helpers ────────────────────────────────────────────────────────

/// Cast `&SBApplication` to `&AnyObject`.
pub(super) fn app_as_any(app: &SBApplication) -> &AnyObject {
    unsafe { &*(app as *const SBApplication as *const AnyObject) }
}

/// Retrieve a ScriptingBridge element collection via `performSelector:`.
///
/// ScriptingBridge routes collection selectors (`notes`, `folders`, `accounts`,
/// `attachments`) through `doesNotUnderstand:`, so they are absent from the static
/// method table. objc2's debug assertions call `responds_to_selector:` before every
/// `msg_send!`, which returns NO for those selectors. Routing through
/// `performSelector:` (a real NSObject method) bypasses that check and lets the
/// ObjC runtime dispatch dynamically.
pub(super) unsafe fn sb_collection(
    obj: &AnyObject,
    sel: objc2::runtime::Sel,
) -> Retained<AnyObject> {
    unsafe { msg_send![obj, performSelector: sel] }
}

/// Get a scripting-dictionary property via KVC (`valueForKey:`).
///
/// `SBObject` implements `valueForKey:` to send Apple Events, so this works for
/// any property in the Notes scripting dictionary without the selector needing to
/// appear in the static method table.
pub(super) unsafe fn kvc_get(obj: &AnyObject, key: &str) -> Option<Retained<AnyObject>> {
    let key_ns = NSString::from_str(key);
    unsafe { msg_send![obj, valueForKey: &*key_ns] }
}

/// Set a string scripting property via KVC (`setValue:forKey:`).
pub(super) unsafe fn kvc_set(obj: &AnyObject, key: &str, value: &str) {
    let key_ns = NSString::from_str(key);
    let val_ns = NSString::from_str(value);
    let _: () = unsafe { msg_send![obj, setValue: &*val_ns, forKey: &*key_ns] };
}

/// Read a scripting property as a plain `String` via KVC + `description`.
/// Works for NSString (returns the string itself) and NSDate (returns its description).
pub(super) unsafe fn kvc_string(obj: &AnyObject, key: &str) -> String {
    match unsafe { kvc_get(obj, key) } {
        None => String::new(),
        Some(val) => {
            let desc: Retained<NSString> = unsafe { msg_send![&*val, description] };
            desc.to_string()
        }
    }
}

/// Read a boolean scripting property via KVC.
/// ScriptingBridge returns boolean values as NSNumber; `charValue` is a real
/// NSNumber method so the debug assertion passes.
pub(super) unsafe fn kvc_bool(obj: &AnyObject, key: &str) -> bool {
    match unsafe { kvc_get(obj, key) } {
        None => false,
        Some(val) => {
            let n: i8 = unsafe { msg_send![&*val, charValue] };
            n != 0
        }
    }
}

/// Return the number of elements in a ScriptingBridge element array.
pub(super) unsafe fn sb_count(arr: &AnyObject) -> usize {
    unsafe { msg_send![arr, count] }
}

/// Return the element at `index` in a ScriptingBridge element array.
pub(super) unsafe fn sb_at(arr: &AnyObject, index: usize) -> Retained<AnyObject> {
    unsafe { msg_send![arr, objectAtIndex: index] }
}

// ─── Collection accessors ─────────────────────────────────────────────────────

pub(super) unsafe fn app_notes(app: &AnyObject) -> Retained<AnyObject> {
    unsafe { sb_collection(app, objc2::sel!(notes)) }
}
pub(super) unsafe fn app_accounts(app: &AnyObject) -> Retained<AnyObject> {
    unsafe { sb_collection(app, objc2::sel!(accounts)) }
}
pub(super) unsafe fn obj_notes(obj: &AnyObject) -> Retained<AnyObject> {
    unsafe { sb_collection(obj, objc2::sel!(notes)) }
}
pub(super) unsafe fn obj_folders(obj: &AnyObject) -> Retained<AnyObject> {
    unsafe { sb_collection(obj, objc2::sel!(folders)) }
}
pub(super) unsafe fn note_attachments(note: &AnyObject) -> Retained<AnyObject> {
    unsafe { sb_collection(note, objc2::sel!(attachments)) }
}

// ─── Object → struct converters ──────────────────────────────────────────────

pub(super) unsafe fn account_info(obj: &AnyObject) -> AccountInfo {
    AccountInfo {
        id: unsafe { kvc_string(obj, "id") },
        name: unsafe { kvc_string(obj, "name") },
    }
}

/// Build a FolderInfo from an SBObject folder proxy.
///
/// `account_name` and `parent_name` are passed by the caller from the traversal
/// context: the container specifier returned by ScriptingBridge from the flat
/// element arrays is unresolved, so we must supply context from the outside.
pub(super) unsafe fn folder_info(
    obj: &AnyObject,
    account_name: &str,
    parent_name: &str,
) -> FolderInfo {
    FolderInfo {
        id: unsafe { kvc_string(obj, "id") },
        name: unsafe { kvc_string(obj, "name") },
        account: account_name.to_owned(),
        parent: parent_name.to_owned(),
    }
}

/// Build a NoteInfo from an SBObject note proxy.
///
/// `folder_name` and `account_name` are passed by the caller (see note above
/// in `folder_info`).
pub(super) unsafe fn note_info(obj: &AnyObject, folder_name: &str, account_name: &str) -> NoteInfo {
    NoteInfo {
        id: unsafe { kvc_string(obj, "id") },
        title: unsafe { kvc_string(obj, "name") },
        body: unsafe { kvc_string(obj, "body") },
        creation_date: unsafe { kvc_string(obj, "creationDate") },
        modification_date: unsafe { kvc_string(obj, "modificationDate") },
        folder: folder_name.to_owned(),
        account: account_name.to_owned(),
        shared: unsafe { kvc_bool(obj, "shared") },
        password_protected: unsafe { kvc_bool(obj, "passwordProtected") },
    }
}

pub(super) unsafe fn attachment_info(obj: &AnyObject, note_title: &str) -> AttachmentInfo {
    AttachmentInfo {
        id: unsafe { kvc_string(obj, "id") },
        name: unsafe { kvc_string(obj, "name") },
        creation_date: unsafe { kvc_string(obj, "creationDate") },
        modification_date: unsafe { kvc_string(obj, "modificationDate") },
        url: unsafe { kvc_string(obj, "URL") },
        note_title: note_title.to_owned(),
    }
}

// ─── Traversal helpers ────────────────────────────────────────────────────────

/// Collect all `FolderInfo` entries from a folder array with the given account context.
/// Recurses into sub-folders.
pub(super) unsafe fn collect_folders(
    folders_arr: &AnyObject,
    account_name: &str,
    parent_name: &str,
    out: &mut Vec<FolderInfo>,
) {
    let count = unsafe { sb_count(folders_arr) };
    for i in 0..count {
        let folder = unsafe { sb_at(folders_arr, i) };
        let fi = unsafe { folder_info(&folder, account_name, parent_name) };
        let folder_name = fi.name.clone();
        out.push(fi);
        let sub_arr = unsafe { obj_folders(&folder) };
        unsafe { collect_folders(&sub_arr, account_name, &folder_name, out) };
    }
}

/// Collect all `NoteInfo` entries from a folder's notes array.
pub(super) unsafe fn collect_notes_in_folder(
    folder: &AnyObject,
    folder_name: &str,
    account_name: &str,
    out: &mut Vec<NoteInfo>,
) {
    let notes_arr = unsafe { obj_notes(folder) };
    let count = unsafe { sb_count(&notes_arr) };
    for i in 0..count {
        let note = unsafe { sb_at(&notes_arr, i) };
        out.push(unsafe { note_info(&note, folder_name, account_name) });
    }
}

/// Collect all `NoteInfo` entries from all folders in a folder array (recursive).
pub(super) unsafe fn collect_notes_in_folders(
    folders_arr: &AnyObject,
    account_name: &str,
    out: &mut Vec<NoteInfo>,
) {
    let count = unsafe { sb_count(folders_arr) };
    for i in 0..count {
        let folder = unsafe { sb_at(folders_arr, i) };
        let folder_name = unsafe { kvc_string(&folder, "name") };
        unsafe { collect_notes_in_folder(&folder, &folder_name, account_name, out) };
        let sub_arr = unsafe { obj_folders(&folder) };
        unsafe { collect_notes_in_folders(&sub_arr, account_name, out) };
    }
}
