use objc2::msg_send;
use objc2::rc::Retained;
use objc2::runtime::{AnyObject, Sel};
use objc2_foundation::{NSArray, NSString};

/// `ns_string!` caches the `NSString` after first use, so repeated property
/// access does not allocate a fresh key object per Apple Event.
pub(super) mod keys {
    use objc2_foundation::{NSString, ns_string};

    macro_rules! key {
        ($fn_name:ident, $key:literal) => {
            #[inline]
            pub(crate) fn $fn_name() -> &'static NSString {
                ns_string!($key)
            }
        };
    }

    key!(id, "id");
    key!(name, "name");
    key!(body, "body");
    key!(creation_date, "creationDate");
    key!(modification_date, "modificationDate");
    key!(shared, "shared");
    key!(password_protected, "passwordProtected");
    key!(url, "URL");
    key!(plaintext, "plaintext");
    key!(default_account, "defaultAccount");
}

/// `SBObject` implements `valueForKey:` by sending an Apple Event, so this
/// reaches any property in the Notes scripting dictionary without the selector
/// needing to exist in the static method table.
pub(super) unsafe fn kvc_get(obj: &AnyObject, key: &NSString) -> Option<Retained<AnyObject>> {
    unsafe { msg_send![obj, valueForKey: key] }
}

/// Non-string values, `NSDate` among them, come back as their `description`.
pub(super) unsafe fn kvc_string(obj: &AnyObject, key: &NSString) -> String {
    match unsafe { kvc_get(obj, key) } {
        None => String::new(),
        Some(val) => unsafe { any_to_string(&val) },
    }
}

pub(super) unsafe fn kvc_bool(obj: &AnyObject, key: &NSString) -> bool {
    match unsafe { kvc_get(obj, key) } {
        None => false,
        Some(val) => unsafe { any_to_bool(&val) },
    }
}

pub(super) unsafe fn kvc_set(obj: &AnyObject, key: &NSString, value: &str) {
    let val = NSString::from_str(value);
    let _: () = unsafe { msg_send![obj, setValue: &*val, forKey: key] };
}

pub(super) unsafe fn sb_count(arr: &AnyObject) -> usize {
    unsafe { msg_send![arr, count] }
}

pub(super) unsafe fn sb_at(arr: &AnyObject, index: usize) -> Retained<AnyObject> {
    unsafe { msg_send![arr, objectAtIndex: index] }
}

/// `valueForKey:` on the *collection* (rather than on each element) is
/// translated by ScriptingBridge into a single "get every element's `key`"
/// Apple Event returning a plain `NSArray`. Cost: 1 Apple Event instead of N.
pub(super) unsafe fn kvc_string_vec(collection: &AnyObject, key: &NSString) -> Vec<String> {
    unsafe { kvc_vec(collection, key, |elem| any_to_string(elem)) }
}

pub(super) unsafe fn kvc_bool_vec(collection: &AnyObject, key: &NSString) -> Vec<bool> {
    unsafe { kvc_vec(collection, key, |elem| any_to_bool(elem)) }
}

/// Comparison happens on the `NSString`s returned by the batch fetch, so
/// looking a note up by title costs one Apple Event and no Rust allocations.
pub(super) unsafe fn kvc_index_of(
    collection: &AnyObject,
    key: &NSString,
    value: &NSString,
) -> Option<usize> {
    let raw = unsafe { kvc_get(collection, key) }?;
    let arr = raw.downcast_ref::<NSArray<AnyObject>>()?;
    arr.iter().position(|elem| {
        elem.downcast_ref::<NSString>()
            .is_some_and(|s| s.isEqualToString(value))
    })
}

unsafe fn kvc_vec<T>(
    collection: &AnyObject,
    key: &NSString,
    convert: impl Fn(&AnyObject) -> T,
) -> Vec<T> {
    let Some(raw) = (unsafe { kvc_get(collection, key) }) else {
        return Vec::new();
    };
    let Some(arr) = raw.downcast_ref::<NSArray<AnyObject>>() else {
        return Vec::new();
    };
    arr.iter().map(|elem| convert(&elem)).collect()
}

unsafe fn any_to_string(val: &AnyObject) -> String {
    match val.downcast_ref::<NSString>() {
        Some(s) => s.to_string(),
        None => {
            let desc: Retained<NSString> = unsafe { msg_send![val, description] };
            desc.to_string()
        }
    }
}

unsafe fn any_to_bool(val: &AnyObject) -> bool {
    let n: i8 = unsafe { msg_send![val, charValue] };
    n != 0
}

/// ScriptingBridge routes collection selectors (`notes`, `folders`, `accounts`,
/// `attachments`) through `doesNotUnderstand:`, so they are absent from the
/// static method table and objc2's debug `responds_to_selector:` assertion
/// rejects them. `performSelector:` is a real `NSObject` method, so it passes
/// the check and lets the runtime dispatch dynamically.
pub(super) unsafe fn sb_collection(obj: &AnyObject, sel: Sel) -> Retained<AnyObject> {
    unsafe { msg_send![obj, performSelector: sel] }
}

/// Same reason as [`sb_collection`]: command selectors generated by
/// ScriptingBridge (`moveTo:` and friends) are not in the static method table.
/// Commands such as `move` are declared `void` in the Notes dictionary, so the
/// return register holds no object: it is read as a raw pointer and dropped,
/// never retained. Callers confirm the effect by reading the result back.
pub(super) unsafe fn sb_command(obj: &AnyObject, sel: Sel, arg: &AnyObject) {
    let _: *mut AnyObject = unsafe { msg_send![obj, performSelector: sel, withObject: arg] };
}

/// `needle` must already be lower-cased by the caller, so a search over a whole
/// library lower-cases the query once rather than once per note.
pub(super) fn contains_ignore_case(haystack: &str, needle: &str) -> bool {
    if needle.is_empty() {
        return true;
    }
    haystack
        .char_indices()
        .any(|(i, _)| starts_with_ignore_case(&haystack[i..], needle))
}

fn starts_with_ignore_case(haystack: &str, needle: &str) -> bool {
    let mut lowered = haystack.chars().flat_map(char::to_lowercase);
    let mut expected = needle.chars();
    loop {
        match (expected.next(), lowered.next()) {
            (None, _) => return true,
            (Some(_), None) => return false,
            (Some(want), Some(got)) if want == got => continue,
            _ => return false,
        }
    }
}

/// Moves the value out, leaving an empty string in the slice, so owned structs
/// can be built from batch-fetched columns without cloning them.
pub(super) fn take_at(values: &mut [String], index: usize) -> String {
    values
        .get_mut(index)
        .map(std::mem::take)
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use objc2::class;
    use objc2_foundation::NSNumber;
    use objc2_foundation::ns_string;

    unsafe fn new_dict() -> Retained<AnyObject> {
        let alloc: *mut AnyObject = msg_send![class!(NSMutableDictionary), alloc];
        let init: *mut AnyObject = msg_send![alloc, init];
        unsafe { Retained::from_raw(init).unwrap() }
    }

    unsafe fn dict_set(obj: &AnyObject, key: &NSString, val: &AnyObject) {
        let _: () = msg_send![obj, setValue: val, forKey: key];
    }

    unsafe fn dict_set_str(obj: &AnyObject, key: &str, val: &str) {
        let k = NSString::from_str(key);
        let v = NSString::from_str(val);
        unsafe { dict_set(obj, &k, &v) };
    }

    unsafe fn dict_set_bool(obj: &AnyObject, key: &str, val: bool) {
        let k = NSString::from_str(key);
        let n: Retained<NSNumber> = msg_send![class!(NSNumber), numberWithBool: val];
        unsafe { dict_set(obj, &k, &n) };
    }

    unsafe fn nsarray(items: &[&str]) -> Retained<AnyObject> {
        if items.is_empty() {
            return msg_send![class!(NSArray), array];
        }
        let strings: Vec<Retained<NSString>> =
            items.iter().map(|&s| NSString::from_str(s)).collect();
        let ptrs: Vec<*const AnyObject> = strings
            .iter()
            .map(|s| s.as_ref() as *const NSString as *const AnyObject)
            .collect();
        msg_send![class!(NSArray), arrayWithObjects: ptrs.as_ptr(), count: ptrs.len()]
    }

    unsafe fn nsarray_bools(items: &[bool]) -> Retained<AnyObject> {
        let numbers: Vec<Retained<NSNumber>> = items
            .iter()
            .map(|&b| msg_send![class!(NSNumber), numberWithBool: b])
            .collect();
        let ptrs: Vec<*const AnyObject> = numbers
            .iter()
            .map(|n| n.as_ref() as *const NSNumber as *const AnyObject)
            .collect();
        if ptrs.is_empty() {
            return msg_send![class!(NSArray), array];
        }
        msg_send![class!(NSArray), arrayWithObjects: ptrs.as_ptr(), count: ptrs.len()]
    }

    /// Shaped like what `valueForKey:` on an SBElementArray returns.
    unsafe fn dict_with_column(key: &str, values: Retained<AnyObject>) -> Retained<AnyObject> {
        let dict = unsafe { new_dict() };
        let k = NSString::from_str(key);
        unsafe { dict_set(&dict, &k, &values) };
        dict
    }

    #[test]
    fn kvc_get_returns_none_for_missing_key() {
        unsafe {
            let dict = new_dict();
            assert!(kvc_get(&dict, ns_string!("missing")).is_none());
        }
    }

    #[test]
    fn kvc_string_returns_empty_for_missing_key() {
        unsafe {
            let dict = new_dict();
            assert_eq!(kvc_string(&dict, ns_string!("missing")), "");
        }
    }

    #[test]
    fn kvc_string_returns_stored_value() {
        unsafe {
            let dict = new_dict();
            dict_set_str(&dict, "name", "Alice");
            assert_eq!(kvc_string(&dict, keys::name()), "Alice");
        }
    }

    #[test]
    fn kvc_string_preserves_unicode() {
        unsafe {
            let dict = new_dict();
            dict_set_str(&dict, "name", "Заметка 📝");
            assert_eq!(kvc_string(&dict, keys::name()), "Заметка 📝");
        }
    }

    #[test]
    fn kvc_string_falls_back_to_description_for_non_strings() {
        unsafe {
            let dict = new_dict();
            let k = NSString::from_str("count");
            let n: Retained<NSNumber> = msg_send![class!(NSNumber), numberWithInt: 42i32];
            dict_set(&dict, &k, &n);
            assert_eq!(kvc_string(&dict, ns_string!("count")), "42");
        }
    }

    #[test]
    fn kvc_bool_returns_false_for_missing_key() {
        unsafe {
            let dict = new_dict();
            assert!(!kvc_bool(&dict, ns_string!("flag")));
        }
    }

    #[test]
    fn kvc_bool_returns_true() {
        unsafe {
            let dict = new_dict();
            dict_set_bool(&dict, "shared", true);
            assert!(kvc_bool(&dict, keys::shared()));
        }
    }

    #[test]
    fn kvc_bool_returns_false() {
        unsafe {
            let dict = new_dict();
            dict_set_bool(&dict, "shared", false);
            assert!(!kvc_bool(&dict, keys::shared()));
        }
    }

    #[test]
    fn kvc_set_stores_value() {
        unsafe {
            let dict = new_dict();
            kvc_set(&dict, keys::body(), "content");
            assert_eq!(kvc_string(&dict, keys::body()), "content");
        }
    }

    #[test]
    fn kvc_set_overwrites_existing_value() {
        unsafe {
            let dict = new_dict();
            kvc_set(&dict, keys::name(), "Old");
            kvc_set(&dict, keys::name(), "New");
            assert_eq!(kvc_string(&dict, keys::name()), "New");
        }
    }

    #[test]
    fn sb_count_empty_array() {
        unsafe {
            assert_eq!(sb_count(&nsarray(&[])), 0);
        }
    }

    #[test]
    fn sb_count_returns_length() {
        unsafe {
            assert_eq!(sb_count(&nsarray(&["a", "b", "c"])), 3);
        }
    }

    #[test]
    fn sb_at_returns_element_at_index() {
        unsafe {
            let arr = nsarray(&["first", "second"]);
            let desc: Retained<NSString> = msg_send![&*sb_at(&arr, 1), description];
            assert_eq!(desc.to_string(), "second");
        }
    }

    #[test]
    fn kvc_string_vec_returns_every_element() {
        unsafe {
            let dict = dict_with_column("name", nsarray(&["a", "b", "c"]));
            assert_eq!(kvc_string_vec(&dict, keys::name()), vec!["a", "b", "c"]);
        }
    }

    #[test]
    fn kvc_string_vec_is_empty_for_missing_key() {
        unsafe {
            let dict = new_dict();
            assert!(kvc_string_vec(&dict, keys::name()).is_empty());
        }
    }

    #[test]
    fn kvc_string_vec_is_empty_for_non_array_value() {
        unsafe {
            let dict = new_dict();
            dict_set_str(&dict, "name", "not an array");
            assert!(kvc_string_vec(&dict, keys::name()).is_empty());
        }
    }

    #[test]
    fn kvc_bool_vec_returns_every_element() {
        unsafe {
            let dict = dict_with_column("shared", nsarray_bools(&[true, false, true]));
            assert_eq!(kvc_bool_vec(&dict, keys::shared()), vec![true, false, true]);
        }
    }

    #[test]
    fn kvc_index_of_finds_matching_element() {
        unsafe {
            let dict = dict_with_column("name", nsarray(&["one", "two", "three"]));
            let target = NSString::from_str("two");
            assert_eq!(kvc_index_of(&dict, keys::name(), &target), Some(1));
        }
    }

    #[test]
    fn kvc_index_of_returns_first_match() {
        unsafe {
            let dict = dict_with_column("name", nsarray(&["dup", "dup"]));
            let target = NSString::from_str("dup");
            assert_eq!(kvc_index_of(&dict, keys::name(), &target), Some(0));
        }
    }

    #[test]
    fn kvc_index_of_is_case_sensitive() {
        unsafe {
            let dict = dict_with_column("name", nsarray(&["Note"]));
            let target = NSString::from_str("note");
            assert_eq!(kvc_index_of(&dict, keys::name(), &target), None);
        }
    }

    #[test]
    fn kvc_index_of_returns_none_when_absent() {
        unsafe {
            let dict = dict_with_column("name", nsarray(&["one"]));
            let target = NSString::from_str("missing");
            assert_eq!(kvc_index_of(&dict, keys::name(), &target), None);
        }
    }

    #[test]
    fn kvc_index_of_returns_none_for_missing_key() {
        unsafe {
            let dict = new_dict();
            let target = NSString::from_str("anything");
            assert_eq!(kvc_index_of(&dict, keys::name(), &target), None);
        }
    }

    #[test]
    fn take_at_moves_the_value_out() {
        let mut values = vec!["a".to_string(), "b".to_string()];
        assert_eq!(take_at(&mut values, 1), "b");
        assert_eq!(values[1], "");
    }

    #[test]
    fn take_at_defaults_when_out_of_range() {
        let mut values: Vec<String> = Vec::new();
        assert_eq!(take_at(&mut values, 5), "");
    }

    #[test]
    fn contains_ignore_case_matches_exactly() {
        assert!(contains_ignore_case("shopping list", "shopping list"));
    }

    #[test]
    fn contains_ignore_case_matches_substring() {
        assert!(contains_ignore_case("weekly shopping list", "shopping"));
    }

    #[test]
    fn contains_ignore_case_ignores_haystack_case() {
        assert!(contains_ignore_case("Shopping LIST", "shopping list"));
    }

    #[test]
    fn contains_ignore_case_matches_at_the_end() {
        assert!(contains_ignore_case("<div>Budget</div>", "</div>"));
    }

    #[test]
    fn contains_ignore_case_rejects_absent_needle() {
        assert!(!contains_ignore_case("shopping list", "groceries"));
    }

    #[test]
    fn contains_ignore_case_rejects_longer_needle() {
        assert!(!contains_ignore_case("ab", "abc"));
    }

    #[test]
    fn contains_ignore_case_accepts_empty_needle() {
        assert!(contains_ignore_case("anything", ""));
        assert!(contains_ignore_case("", ""));
    }

    #[test]
    fn contains_ignore_case_rejects_needle_in_empty_haystack() {
        assert!(!contains_ignore_case("", "a"));
    }

    #[test]
    fn contains_ignore_case_handles_non_ascii() {
        assert!(contains_ignore_case("Список Покупок", "покупок"));
        assert!(!contains_ignore_case("Список", "покупок"));
    }

    #[test]
    fn contains_ignore_case_respects_multibyte_boundaries() {
        assert!(contains_ignore_case("naïve café", "café"));
        assert!(contains_ignore_case("🎯 target", "target"));
    }
}
