//! Apple Notes CRUD via macOS ScriptingBridge.framework.
//!
//! All public functions are synchronous blocking calls; they send Apple Events
//! to Notes.app in-process through the Scripting Bridge — no subprocess is spawned.

#![allow(non_snake_case)]

use anyhow::{anyhow, Context, Result};
use serde::{Deserialize, Serialize};

use objc2::rc::Retained;
use objc2::runtime::AnyObject;
use objc2::{extern_class, msg_send, ClassType};
use objc2_foundation::{NSObject, NSString};

// ─── Link ScriptingBridge framework ──────────────────────────────────────────

#[link(name = "ScriptingBridge", kind = "framework")]
unsafe extern "C" {}

// ─── Minimal ScriptingBridge class declarations ───────────────────────────────
//
// objc2 has no pre-generated crate for ScriptingBridge, so we declare the two
// root classes manually.  Notes-specific proxy types are generated by the runtime
// and accessed as AnyObject.

extern_class!(
    #[unsafe(super(NSObject))]
    pub struct SBObject;
);

extern_class!(
    #[unsafe(super(SBObject, NSObject))]
    pub struct SBApplication;
);

// ─── Public data types ────────────────────────────────────────────────────────

/// Account (e.g. "iCloud", "On My Mac").
#[derive(Debug, Serialize, Deserialize)]
pub struct AccountInfo {
    /// Unique scripting ID of the account.
    pub id: String,
    pub name: String,
    /// Whether the account has been upgraded to the latest Notes format.
    pub upgraded: bool,
}

/// A Notes folder (may be nested inside another folder or directly under an account).
#[derive(Debug, Serialize, Deserialize)]
pub struct FolderInfo {
    /// Unique scripting ID of the folder.
    pub id: String,
    pub name: String,
    pub shared: bool,
    /// Name of the containing account (top-level container).
    pub account: String,
    /// Name of the immediate parent (account name or another folder name).
    pub parent: String,
}

/// Full metadata and content of a single note.
#[derive(Debug, Serialize, Deserialize)]
pub struct NoteInfo {
    /// Unique scripting ID of the note.
    pub id: String,
    pub title: String,
    /// HTML body of the note.
    pub body: String,
    /// Plain-text body (HTML stripped).
    pub plaintext: String,
    pub creation_date: String,
    pub modification_date: String,
    /// Containing folder name.
    pub folder: String,
    /// Containing account name (top-level).
    pub account: String,
    pub shared: bool,
    pub password_protected: bool,
}

/// A file attachment embedded in a note.
#[derive(Debug, Serialize, Deserialize)]
pub struct AttachmentInfo {
    /// Unique scripting ID of the attachment.
    pub id: String,
    pub name: String,
    /// UTI-based content identifier.
    pub content_identifier: String,
    pub creation_date: String,
    pub modification_date: String,
    /// File URL of the attachment (may be empty for inline attachments).
    pub url: String,
    pub shared: bool,
    /// Title of the note that contains this attachment.
    pub note_title: String,
}

// ─── Low-level helpers ────────────────────────────────────────────────────────

/// Obtain a live ScriptingBridge proxy to Notes.app.
fn notes_app() -> Result<Retained<SBApplication>> {
    let bundle_id = NSString::from_str("com.apple.Notes");
    let app: Option<Retained<SBApplication>> = unsafe {
        msg_send![SBApplication::class(), applicationWithBundleIdentifier: &*bundle_id]
    };
    app.ok_or_else(|| anyhow!("Cannot connect to Apple Notes via ScriptingBridge"))
}

/// Retrieve a ScriptingBridge element collection via `performSelector:`.
///
/// ScriptingBridge routes collection selectors (`notes`, `folders`, `accounts`,
/// `attachments`) through `doesNotUnderstand:`, so they are absent from the static
/// method table. objc2's debug assertions call `responds_to_selector:` before every
/// `msg_send!`, which returns NO for those selectors. Routing through
/// `performSelector:` (a real NSObject method) bypasses that check and lets the
/// ObjC runtime dispatch dynamically.
unsafe fn sb_collection(obj: &AnyObject, sel: objc2::runtime::Sel) -> Retained<AnyObject> {
    unsafe { msg_send![obj, performSelector: sel] }
}

/// Cast `&SBApplication` to `&AnyObject`.
fn app_as_any(app: &SBApplication) -> &AnyObject {
    unsafe { &*(app as *const SBApplication as *const AnyObject) }
}

/// Get a scripting-dictionary property via KVC (`valueForKey:`).
///
/// `SBObject` implements `valueForKey:` to send Apple Events, so this works for
/// any property in the Notes scripting dictionary without the selector needing to
/// appear in the static method table.
unsafe fn kvc_get(obj: &AnyObject, key: &str) -> Option<Retained<AnyObject>> {
    let key_ns = NSString::from_str(key);
    unsafe { msg_send![obj, valueForKey: &*key_ns] }
}

/// Set a string scripting property via KVC (`setValue:forKey:`).
unsafe fn kvc_set(obj: &AnyObject, key: &str, value: &str) {
    let key_ns = NSString::from_str(key);
    let val_ns = NSString::from_str(value);
    let _: () = unsafe { msg_send![obj, setValue: &*val_ns, forKey: &*key_ns] };
}

/// Read a scripting property as a plain `String` via KVC + `description`.
/// Works for NSString (returns the string itself) and NSDate (returns its description).
unsafe fn kvc_string(obj: &AnyObject, key: &str) -> String {
    match unsafe { kvc_get(obj, key) } {
        None => String::new(),
        Some(val) => {
            let desc: Retained<NSString> = unsafe { msg_send![&*val, description] };
            desc.to_string()
        }
    }
}

/// Read a boolean scripting property via KVC.
/// ScriptingBridge returns boolean values as NSNumber; `charValue` is a real
/// NSNumber method so the debug assertion passes.
unsafe fn kvc_bool(obj: &AnyObject, key: &str) -> bool {
    match unsafe { kvc_get(obj, key) } {
        None => false,
        Some(val) => {
            let n: i8 = unsafe { msg_send![&*val, charValue] };
            n != 0
        }
    }
}

/// Return the number of elements in a ScriptingBridge element array.
unsafe fn sb_count(arr: &AnyObject) -> usize {
    unsafe { msg_send![arr, count] }
}

/// Return the element at `index` in a ScriptingBridge element array.
unsafe fn sb_at(arr: &AnyObject, index: usize) -> Retained<AnyObject> {
    unsafe { msg_send![arr, objectAtIndex: index] }
}

// ─── Collection accessors ─────────────────────────────────────────────────────

unsafe fn app_notes(app: &AnyObject) -> Retained<AnyObject> {
    unsafe { sb_collection(app, objc2::sel!(notes)) }
}
unsafe fn app_folders(app: &AnyObject) -> Retained<AnyObject> {
    unsafe { sb_collection(app, objc2::sel!(folders)) }
}
unsafe fn app_accounts(app: &AnyObject) -> Retained<AnyObject> {
    unsafe { sb_collection(app, objc2::sel!(accounts)) }
}
unsafe fn obj_notes(obj: &AnyObject) -> Retained<AnyObject> {
    unsafe { sb_collection(obj, objc2::sel!(notes)) }
}
unsafe fn obj_folders(obj: &AnyObject) -> Retained<AnyObject> {
    unsafe { sb_collection(obj, objc2::sel!(folders)) }
}
unsafe fn note_attachments(note: &AnyObject) -> Retained<AnyObject> {
    unsafe { sb_collection(note, objc2::sel!(attachments)) }
}

// ─── Object → struct converters ──────────────────────────────────────────────

unsafe fn account_info(obj: &AnyObject) -> AccountInfo {
    AccountInfo {
        id: unsafe { kvc_string(obj, "id") },
        name: unsafe { kvc_string(obj, "name") },
        upgraded: unsafe { kvc_bool(obj, "upgraded") },
    }
}

/// Build a FolderInfo from an SBObject folder proxy.
///
/// `account_name` and `parent_name` are passed by the caller from the traversal
/// context: the container specifier returned by ScriptingBridge from the flat
/// element arrays is unresolved, so we must supply context from the outside.
unsafe fn folder_info(obj: &AnyObject, account_name: &str, parent_name: &str) -> FolderInfo {
    FolderInfo {
        id: unsafe { kvc_string(obj, "id") },
        name: unsafe { kvc_string(obj, "name") },
        shared: unsafe { kvc_bool(obj, "shared") },
        account: account_name.to_owned(),
        parent: parent_name.to_owned(),
    }
}

/// Build a NoteInfo from an SBObject note proxy.
///
/// `folder_name` and `account_name` are passed by the caller (see note above
/// in `folder_info`).
unsafe fn note_info(obj: &AnyObject, folder_name: &str, account_name: &str) -> NoteInfo {
    NoteInfo {
        id: unsafe { kvc_string(obj, "id") },
        title: unsafe { kvc_string(obj, "name") },
        body: unsafe { kvc_string(obj, "body") },
        plaintext: unsafe { kvc_string(obj, "plaintext") },
        creation_date: unsafe { kvc_string(obj, "creationDate") },
        modification_date: unsafe { kvc_string(obj, "modificationDate") },
        folder: folder_name.to_owned(),
        account: account_name.to_owned(),
        shared: unsafe { kvc_bool(obj, "shared") },
        password_protected: unsafe { kvc_bool(obj, "passwordProtected") },
    }
}

unsafe fn attachment_info(obj: &AnyObject, note_title: &str) -> AttachmentInfo {
    AttachmentInfo {
        id: unsafe { kvc_string(obj, "id") },
        name: unsafe { kvc_string(obj, "name") },
        content_identifier: unsafe { kvc_string(obj, "contentIdentifier") },
        creation_date: unsafe { kvc_string(obj, "creationDate") },
        modification_date: unsafe { kvc_string(obj, "modificationDate") },
        url: unsafe { kvc_string(obj, "URL") },
        shared: unsafe { kvc_bool(obj, "shared") },
        note_title: note_title.to_owned(),
    }
}

// ─── Traversal helpers ────────────────────────────────────────────────────────

/// Collect all `FolderInfo` entries from a folder array with the given account context.
/// Recurses into sub-folders.
unsafe fn collect_folders(
    folders_arr: &AnyObject,
    account_name: &str,
    parent_name: &str,
    out: &mut Vec<FolderInfo>,
) {
    let count = unsafe { sb_count(folders_arr) };
    for i in 0..count {
        let folder = unsafe { sb_at(folders_arr, i) };
        let fi = unsafe { folder_info(&folder, account_name, parent_name) };
        let folder_name = fi.name.clone();
        out.push(fi);
        // Recurse into sub-folders
        let sub_arr = unsafe { obj_folders(&folder) };
        unsafe { collect_folders(&sub_arr, account_name, &folder_name, out) };
    }
}

/// Collect all `NoteInfo` entries from a folder's notes array.
unsafe fn collect_notes_in_folder(
    folder: &AnyObject,
    folder_name: &str,
    account_name: &str,
    out: &mut Vec<NoteInfo>,
) {
    let notes_arr = unsafe { obj_notes(folder) };
    let count = unsafe { sb_count(&notes_arr) };
    for i in 0..count {
        let note = unsafe { sb_at(&notes_arr, i) };
        out.push(unsafe { note_info(&note, folder_name, account_name) });
    }
}

/// Collect all `NoteInfo` entries from all folders in a folder array (recursive).
unsafe fn collect_notes_in_folders(
    folders_arr: &AnyObject,
    account_name: &str,
    out: &mut Vec<NoteInfo>,
) {
    let count = unsafe { sb_count(folders_arr) };
    for i in 0..count {
        let folder = unsafe { sb_at(folders_arr, i) };
        let folder_name = unsafe { kvc_string(&folder, "name") };
        unsafe { collect_notes_in_folder(&folder, &folder_name, account_name, out) };
        // Recurse into sub-folders
        let sub_arr = unsafe { obj_folders(&folder) };
        unsafe { collect_notes_in_folders(&sub_arr, account_name, out) };
    }
}

// ─── Public read API ──────────────────────────────────────────────────────────

/// Return all accounts configured in Apple Notes.
pub fn list_accounts() -> Result<Vec<AccountInfo>> {
    let app = notes_app()?;
    unsafe {
        let arr = app_accounts(app_as_any(&app));
        let count = sb_count(&arr);
        let mut out = Vec::with_capacity(count);
        for i in 0..count {
            out.push(account_info(&sb_at(&arr, i)));
        }
        Ok(out)
    }
}

/// Return all folders across all accounts (including subfolders).
pub fn list_folders() -> Result<Vec<FolderInfo>> {
    let app = notes_app()?;
    unsafe {
        let accounts_arr = app_accounts(app_as_any(&app));
        let account_count = sb_count(&accounts_arr);
        let mut out = Vec::new();
        for i in 0..account_count {
            let account = sb_at(&accounts_arr, i);
            let account_name = kvc_string(&account, "name");
            let folders_arr = obj_folders(&account);
            collect_folders(&folders_arr, &account_name, &account_name, &mut out);
        }
        Ok(out)
    }
}

/// Return just the titles of all notes (fast — avoids fetching body/plaintext).
pub fn list_notes() -> Result<Vec<String>> {
    let app = notes_app()?;
    unsafe {
        let arr = app_notes(app_as_any(&app));
        let count = sb_count(&arr);
        let mut out = Vec::with_capacity(count);
        for i in 0..count {
            out.push(kvc_string(&sb_at(&arr, i), "name"));
        }
        Ok(out)
    }
}

/// Return full metadata + content for every note.
/// Iterates accounts → folders → notes to resolve folder/account context.
pub fn get_all_notes() -> Result<Vec<NoteInfo>> {
    let app = notes_app()?;
    unsafe {
        let accounts_arr = app_accounts(app_as_any(&app));
        let account_count = sb_count(&accounts_arr);
        let mut out = Vec::new();
        for i in 0..account_count {
            let account = sb_at(&accounts_arr, i);
            let account_name = kvc_string(&account, "name");
            let folders_arr = obj_folders(&account);
            collect_notes_in_folders(&folders_arr, &account_name, &mut out);
        }
        Ok(out)
    }
}

/// Return the full details of a note by title, or `None` if not found.
pub fn get_note_by_title(title: &str) -> Result<Option<NoteInfo>> {
    let app = notes_app()?;
    unsafe {
        let accounts_arr = app_accounts(app_as_any(&app));
        let account_count = sb_count(&accounts_arr);
        for i in 0..account_count {
            let account = sb_at(&accounts_arr, i);
            let account_name = kvc_string(&account, "name");
            let folders_arr = obj_folders(&account);
            let folder_count = sb_count(&folders_arr);
            for j in 0..folder_count {
                let folder = sb_at(&folders_arr, j);
                let folder_name = kvc_string(&folder, "name");
                let notes_arr = obj_notes(&folder);
                let note_count = sb_count(&notes_arr);
                for k in 0..note_count {
                    let note = sb_at(&notes_arr, k);
                    if kvc_string(&note, "name") == title {
                        return Ok(Some(note_info(&note, &folder_name, &account_name)));
                    }
                }
            }
        }
        Ok(None)
    }
}

/// Return all notes inside a specific folder (matched by folder name).
pub fn get_notes_in_folder(folder_name: &str) -> Result<Vec<NoteInfo>> {
    let app = notes_app()?;
    unsafe {
        let accounts_arr = app_accounts(app_as_any(&app));
        let account_count = sb_count(&accounts_arr);
        for i in 0..account_count {
            let account = sb_at(&accounts_arr, i);
            let account_name = kvc_string(&account, "name");
            let folders_arr = obj_folders(&account);
            let folder_count = sb_count(&folders_arr);
            for j in 0..folder_count {
                let folder = sb_at(&folders_arr, j);
                if kvc_string(&folder, "name") == folder_name {
                    let mut out = Vec::new();
                    collect_notes_in_folder(&folder, folder_name, &account_name, &mut out);
                    return Ok(out);
                }
            }
        }
        Ok(vec![])
    }
}

/// Return all notes inside a specific account (matched by account name).
pub fn get_notes_in_account(account_name: &str) -> Result<Vec<NoteInfo>> {
    let app = notes_app()?;
    unsafe {
        let accounts_arr = app_accounts(app_as_any(&app));
        let account_count = sb_count(&accounts_arr);
        for i in 0..account_count {
            let account = sb_at(&accounts_arr, i);
            if kvc_string(&account, "name") == account_name {
                let mut out = Vec::new();
                let folders_arr = obj_folders(&account);
                collect_notes_in_folders(&folders_arr, account_name, &mut out);
                return Ok(out);
            }
        }
        Ok(vec![])
    }
}

/// Return all subfolders of a given folder (matched by name), including nested ones.
pub fn get_subfolders(folder_name: &str) -> Result<Vec<FolderInfo>> {
    let app = notes_app()?;
    unsafe {
        let accounts_arr = app_accounts(app_as_any(&app));
        let account_count = sb_count(&accounts_arr);
        for i in 0..account_count {
            let account = sb_at(&accounts_arr, i);
            let account_name = kvc_string(&account, "name");
            let folders_arr = obj_folders(&account);
            let folder_count = sb_count(&folders_arr);
            for j in 0..folder_count {
                let folder = sb_at(&folders_arr, j);
                if kvc_string(&folder, "name") == folder_name {
                    let mut out = Vec::new();
                    let sub_arr = obj_folders(&folder);
                    collect_folders(&sub_arr, &account_name, folder_name, &mut out);
                    return Ok(out);
                }
            }
        }
        Ok(vec![])
    }
}

/// Return all attachments for a note (matched by title).
pub fn get_note_attachments_by_title(title: &str) -> Result<Vec<AttachmentInfo>> {
    let app = notes_app()?;
    unsafe {
        let arr = app_notes(app_as_any(&app));
        let count = sb_count(&arr);
        for i in 0..count {
            let note = sb_at(&arr, i);
            let note_title = kvc_string(&note, "name");
            if note_title == title {
                let att_arr = note_attachments(&note);
                let att_count = sb_count(&att_arr);
                let mut out = Vec::with_capacity(att_count);
                for j in 0..att_count {
                    out.push(attachment_info(&sb_at(&att_arr, j), &note_title));
                }
                return Ok(out);
            }
        }
        Ok(vec![])
    }
}

/// Return every attachment from every note.
pub fn get_all_attachments() -> Result<Vec<AttachmentInfo>> {
    let app = notes_app()?;
    unsafe {
        let notes_arr = app_notes(app_as_any(&app));
        let note_count = sb_count(&notes_arr);
        let mut out = Vec::new();
        for i in 0..note_count {
            let note = sb_at(&notes_arr, i);
            let note_title = kvc_string(&note, "name");
            let att_arr = note_attachments(&note);
            let att_count = sb_count(&att_arr);
            for j in 0..att_count {
                out.push(attachment_info(&sb_at(&att_arr, j), &note_title));
            }
        }
        Ok(out)
    }
}

// ─── Public write API ─────────────────────────────────────────────────────────

/// Create a new note with the given title and HTML body in the default folder.
pub fn create_note(title: &str, content: &str) -> Result<()> {
    let app = notes_app()?;
    unsafe {
        // Ask the Notes scripting dictionary for the "note" proxy class.
        let class_name = NSString::from_str("note");
        let note_cls: Option<Retained<AnyObject>> =
            msg_send![&*app, classForScriptingClass: &*class_name];
        let note_cls =
            note_cls.context("Notes scripting class 'note' not found — is Notes.app installed?")?;

        // alloc + init via raw pointers (objc2 reserves Allocated<T> for typed paths).
        let raw_alloc: *mut AnyObject = msg_send![&*note_cls, alloc];
        let raw_init: *mut AnyObject = msg_send![raw_alloc, init];
        let note = Retained::from_raw(raw_init)
            .ok_or_else(|| anyhow!("Failed to instantiate note object"))?;

        // Insert into the element array → ScriptingBridge sends the Apple Event.
        let arr = app_notes(app_as_any(&app));
        let _: () = msg_send![&*arr, insertObject: &*note, atIndex: 0usize];

        // Use KVC: setName:/setBody: are ScriptingBridge-generated and absent from
        // the static method table — same issue as the collection accessors above.
        kvc_set(&note, "name", title);
        kvc_set(&note, "body", content);
    }
    Ok(())
}

/// Update title and/or body of an existing note (looked up by current title).
/// Returns `false` if no note with `title` exists.
pub fn update_note(title: &str, new_title: Option<&str>, content: Option<&str>) -> Result<bool> {
    let app = notes_app()?;
    unsafe {
        let arr = app_notes(app_as_any(&app));
        let count = sb_count(&arr);
        for i in 0..count {
            let note = sb_at(&arr, i);
            if kvc_string(&note, "name") == title {
                if let Some(t) = new_title {
                    kvc_set(&note, "name", t);
                }
                if let Some(c) = content {
                    kvc_set(&note, "body", c);
                }
                return Ok(true);
            }
        }
        Ok(false)
    }
}

/// Permanently delete a note by title.
/// Returns `false` if no note with `title` exists.
pub fn delete_note(title: &str) -> Result<bool> {
    let app = notes_app()?;
    unsafe {
        let arr = app_notes(app_as_any(&app));
        let count = sb_count(&arr);
        for i in 0..count {
            let note = sb_at(&arr, i);
            if kvc_string(&note, "name") == title {
                // `delete:` is ScriptingBridge-generated; use performSelector:withObject:.
                let sel = objc2::sel!(delete:);
                let _: () =
                    msg_send![app_as_any(&app), performSelector: sel, withObject: &*note];
                return Ok(true);
            }
        }
        Ok(false)
    }
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_list_notes() {
        let notes = list_notes().unwrap();
        assert!(notes.len() > 0);
    }

    #[test]
    fn test_list_accounts() {
        let accounts = list_accounts().unwrap();
        assert!(accounts.len() > 0);
        for a in &accounts {
            assert!(!a.name.is_empty(), "account name should not be empty");
            assert!(!a.id.is_empty(), "account id should not be empty");
        }
    }

    #[test]
    fn test_list_folders() {
        let folders = list_folders().unwrap();
        assert!(folders.len() > 0);
        for f in &folders {
            assert!(!f.name.is_empty(), "folder name should not be empty");
            assert!(!f.account.is_empty(), "folder account should not be empty: {f:?}");
        }
    }

    #[test]
    fn test_get_all_notes() {
        let notes = get_all_notes().unwrap();
        assert!(notes.len() > 0);
        let first = &notes[0];
        assert!(!first.title.is_empty());
        assert!(!first.id.is_empty());
        assert!(!first.creation_date.is_empty());
        assert!(!first.folder.is_empty(), "folder empty: {first:?}");
        assert!(!first.account.is_empty(), "account empty: {first:?}");
    }

    #[test]
    fn test_get_note_by_title() {
        let titles = list_notes().unwrap();
        if let Some(title) = titles.first() {
            let note = get_note_by_title(title).unwrap();
            assert!(note.is_some(), "note should be found by its own title");
            let note = note.unwrap();
            assert_eq!(&note.title, title);
            assert!(!note.id.is_empty());
            assert!(!note.folder.is_empty(), "folder empty for note: {note:?}");
        }
    }
}
